version: '3.8'

services:
  vite-react-app:
    image: node:22.14.0
    container_name: vite-react-container
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules from host
    ports:
      - "5173:5173"  # Vite default port
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped
